language: java
sudo: required

services:
  - docker
  
jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

script:
  - gradle build docker

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - gradle dockerPush