language: java
sudo: required

services:
  - docker
  
jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master
    - h2

cache:
  directories:
  - $HOME/.gradle

script:
  - gradle build docker

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS https://index.docker.io/v1/
  - gradle dockerTag dockerPush -i